[phases.setup]
nixPkgs = ["python311Full", "ffmpeg"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]