[phases.setup]
nixPkgs = ["python311Full", "ffmpeg", "nodejs_20"]

[phases.build]
env = { PYTHON_PACKAGES = "fastapi uvicorn yt-dlp ffmpeg-python" }

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]